In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [6]:
b = np.array([[1,2,3],[4,5,6]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.shape

(2, 3)

In [9]:
a.shape

(3,)

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.dtype

dtype('int32')

In [12]:
#number of rows present
b.ndim

2

In [13]:
#what is the type 
print(type(a))

<class 'numpy.ndarray'>


In [14]:
print(type(b))

<class 'numpy.ndarray'>


In [15]:
#staring from 09 and go upto 99
#arange([start,] stop[, step,], dtype=None)
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
c = range(10000)

In [17]:
%timeit [i**3 for i in c]

2.73 ms ± 4.64 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
c_numpy = np.arange(10000)

In [19]:
%timeit c_numpy**3

13.3 µs ± 9.86 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [22]:
%timeit list(map(lambda x,y: x*y , l1,l2))

873 µs ± 4.82 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
a1 = np.array(l1)
b1 = np.array(l2)

In [24]:
%timeit a1*b1

6.77 µs ± 18.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.arange(2,12,2)


array([ 2,  4,  6,  8, 10])

In [28]:
#3 rows 2 columns of zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
#crease identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#filling values in (a,b) ,  with walue c
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [33]:
np.full((3,3),2.2,dtype = np.int)  #converting floating to int

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [34]:
np.diag([1,2,3,4,5])   #creating sq matrix with diag elements defined

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [35]:
v = np.array([1,2,3])

In [36]:
v

array([1, 2, 3])

In [37]:
# I want to horizontally stack it
np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [38]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [42]:
np.random.random()     #returns value between 0 and 1

0.9423018228113914

In [45]:
# we want rand value from 2 to 50
50 * np.random.random()   + 2

43.93874569710693

In [46]:
np.random.random([3,3])

array([[0.20079032, 0.91759392, 0.87488456],
       [0.51834099, 0.61465309, 0.92380965],
       [0.54256752, 0.22757017, 0.85514813]])

In [47]:
#i want value from 1 to 50 , equally distribuated into 100 parts
a = np.linspace(1,50,100)

In [48]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [49]:
# how much memory is being used by this
a.itemsize
#it has taken up 8 bytes

8

In [50]:
np.arange(18).shape

(18,)

In [51]:
#i want to make it 3d shape
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [52]:
#after 2,3 we dont know what number is so we put -1 and it will automatically do the calc
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [53]:
#what if i want to access element from it
a=np.array([2,4,6,10,12,14,16])

In [54]:
#I want to bring out 2
a[0]

2

In [55]:
a[2]

6

In [57]:
a[[2,4,6]]

array([ 6, 12, 16])

In [58]:
#print out of a from 2nd index
a[2:]

array([ 6, 10, 12, 14, 16])

In [60]:
#print value hooping over wvery 2 values
a[0::2]

array([ 2,  6, 12, 16])

In [61]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a[2,2]

9

In [64]:
a>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [65]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [67]:
a[(a>2) & (a<5)]

array([3, 4])

In [68]:
#subset of array
a = np.arange(10)

In [69]:
b=a

In [70]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
b[0] = 11

In [72]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [73]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [74]:
#value of a also got changed when b gets changed
np.shares_memory(a,b)

True

In [75]:
# they both share the same part of memory
# how to handle this?
a = np.arange(10)
b = a.copy()

In [76]:
b[0] = 11

In [77]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [78]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.shares_memory(a,b)

False

In [80]:
a = np.array([[1,2,3],[4,5,6]])

In [81]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
#i want to transpose it
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [83]:
b = np.array([[7,8,9],[10,11,12]])

In [84]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [87]:
a == b

array([[False, False, False],
       [False, False, False]])

In [89]:
#i want to vertically stack one over other
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [90]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [91]:
a = np.arange(1,10)

In [92]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [94]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.sum(a)

45

In [96]:
np.median(a)

5.0

In [97]:
np.std(a) 

2.581988897471611

In [98]:
a.std()

2.581988897471611

In [100]:
a = np.arange(1,10).reshape(3,3)

In [101]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
#get determinanat or inverse
np.linalg.det(a)

-9.51619735392994e-16

In [103]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [104]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [105]:
b = a.T

In [107]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [108]:
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [109]:
a = np.array([1,1,0],dtype = bool)
b= np.array([1,0,1],dtype = bool)

In [110]:
np.logical_or(a,b)

array([ True,  True,  True])

In [111]:
np.logical_and(a,b)

array([ True, False, False])

In [112]:
a==a

array([ True,  True,  True])

In [113]:
np.all(a == a)

True

In [114]:
a = np.array([[1,2],[3,4]])

In [115]:
a.sum()

10

In [116]:
a.sum(axis = 0)

array([4, 6])

In [117]:
a.sum(axis = 1)

array([3, 7])

In [118]:
a.max()

4

In [119]:
a.argmax()  #index at which max value is

3

In [120]:
a.shape

(2, 2)

In [121]:
a

array([[1, 2],
       [3, 4]])

In [125]:
a  =np.arange(1,10)

In [126]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
a.shape

(9,)

In [128]:
a[:,np.newaxis].shape

(9, 1)

In [129]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.argsort(a) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)